apiVersion: apps/v1
kind: Deployment
metadata:
  name: estoque-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: estoque-service
  template:
    metadata:
      labels:
        app: estoque-service
    spec:
      containers:
        - name: estoque-service
          image: estoque-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8082
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secret
