apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  CLIENTE_SERVICE_HOST: cliente-service
  CLIENTE_SERVICE_PORT: "8082"
  ESTOQUE_SERVICE_HOST: estoque-service
  ESTOQUE_SERVICE_PORT: "8083"
