apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: bW9uZ291c2Vy
  MONGO_INITDB_ROOT_PASSWORD: bW9uZ29wYXNz
  SPRING_DATA_MONGODB_USERNAME: bW9uZ291c2Vy
  SPRING_DATA_MONGODB_PASSWORD: bW9uZ29wYXNz
