apiVersion: apps/v1
kind: Deployment
metadata:
  name: cliente-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cliente-service
  template:
    metadata:
      labels:
        app: cliente-service
    spec:
      containers:
        - name: cliente-service
          image: cliente-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secret
